[package]
name = "mmtk_openjdk"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk_openjdk"
# be careful - LTO is only allowed for certain crate types
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
libc = "0.2"
lazy_static = "1.1"
mmtk = { git = "ssh://git@github.com/mmtk/mmtk-core.git", branch = "master" }
# Uncomment the following to build locally
# mmtk = { path = "../repos/mmtk-core" }

[features]
default = []
nogc = ["mmtk/nogc"]
semispace = ["mmtk/semispace"]