[package]
name = "mmtk_openjdk"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk_openjdk"
# be careful - LTO is only allowed for certain crate types
crate-type = ["rlib", "dylib", "staticlib"]

[profile.release]
lto = true

[dependencies]
libc = "0.2"
lazy_static = "1.1"

[dependencies.mmtk]
git = "https://gitlab.anu.edu.au/mmtk/mmtk-core.git"
rev = "69223ba4f7b0465183e63c005828c33a25bdf467"

[features]
default = []
nogc = ["mmtk/nogc"]
semispace = ["mmtk/semispace"]