variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  script:
    - sed -i 's,ssh://git,https://'$DEPLOY_TOKEN_NAME':'$DEPLOY_TOKEN_PASS',g' mmtk/Cargo.toml
    - cargo +nightly build --manifest-path mmtk/Cargo.toml --features nogc
    - cargo +nightly build --manifest-path mmtk/Cargo.toml --features semispace
